// Generates src/client/gen-univer-css.ts bundling the Univer preset
// stylesheets the viewer needs into one committed TypeScript constant, so the
// classic-script client bundle can inject them without runtime asset URLs.
// Run from this package root whenever the Univer baseline changes:
//   node scripts/gen-css.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const SHEETS = [
  "@univerjs/preset-sheets-core/lib/index.css",
  "@univerjs/preset-sheets-advanced/lib/index.css",
  "@univerjs/preset-sheets-drawing/lib/index.css",
  "@univerjs/preset-sheets-conditional-formatting/lib/index.css",
  "@univerjs/preset-sheets-filter/lib/index.css",
  "@univerjs/preset-sheets-hyper-link/lib/index.css",
  "@univerjs/preset-sheets-data-validation/lib/index.css",
  "@univerjs/preset-sheets-find-replace/lib/index.css",
  "@univerjs/preset-sheets-note/lib/index.css",
  "@univerjs/preset-sheets-sort/lib/index.css",
  "@univerjs/preset-sheets-table/lib/index.css",
  "@univerjs/preset-sheets-thread-comment/lib/index.css",
  "@univerjs-pro/collaboration-client-ui/lib/index.css",
  "@univerjs-pro/embed-ui/lib/index.css",
];

let out = "// GENERATED by scripts/gen-css.mjs — do not edit.\n";
out += "/** Aggregated Univer preset styles for the DSH-page document viewer. */\n";
out += "export const UNIVER_VIEWER_CSS =\n";
for (const spec of SHEETS) {
  const css = readFileSync(require.resolve(spec), "utf8");
  out += `  // ${spec}\n  ${JSON.stringify(css)} +\n`;
}
out += '  "";\n';
writeFileSync(new URL("../src/client/gen-univer-css.ts", import.meta.url), out);
console.log("[gen-css] wrote", SHEETS.length, "stylesheets");
