// Generates src/client/gen-univer.css bundling the Univer preset stylesheets
// the viewer needs into one committed CSS asset, so the classic-script client
// bundle can inject them without runtime asset URLs or CSS strings in TS.
// Run from this package root whenever the Univer baseline changes:
//   node scripts/gen-css.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const SHEETS = [
  // Shared render/workbench styles.
  "@univerjs/design/lib/index.css",
  "@univerjs/ui/lib/index.css",
  "@univerjs/docs-ui/lib/index.css",
  "@univerjs/drawing-ui/lib/index.css",
  "@univerjs-pro/chart-ui/lib/index.css",
  "@univerjs-pro/shape-editor-ui/lib/index.css",
  // Sheet presets.
  "@univerjs/preset-sheets-core/lib/index.css",
  "@univerjs/preset-sheets-advanced/lib/index.css",
  "@univerjs/preset-sheets-drawing/lib/index.css",
  "@univerjs/preset-sheets-conditional-formatting/lib/index.css",
  "@univerjs/preset-sheets-filter/lib/index.css",
  "@univerjs/preset-sheets-hyper-link/lib/index.css",
  "@univerjs/preset-sheets-data-validation/lib/index.css",
  "@univerjs/preset-sheets-find-replace/lib/index.css",
  "@univerjs/preset-sheets-note/lib/index.css",
  "@univerjs/preset-sheets-sort/lib/index.css",
  "@univerjs/preset-sheets-table/lib/index.css",
  "@univerjs/preset-sheets-thread-comment/lib/index.css",
  "@univerjs/preset-sheets-collaboration/lib/index.css",
  // Docs presets and feature controls.
  "@univerjs/preset-docs-core/lib/index.css",
  "@univerjs/preset-docs-drawing/lib/index.css",
  "@univerjs/preset-docs-hyper-link/lib/index.css",
  "@univerjs/preset-docs-thread-comment/lib/index.css",
  "@univerjs-pro/docs-callout-ui/lib/index.css",
  "@univerjs-pro/docs-chart-ui/lib/index.css",
  "@univerjs-pro/docs-code-ui/lib/index.css",
  "@univerjs-pro/docs-column-ui/lib/index.css",
  "@univerjs-pro/docs-latex-ui/lib/index.css",
  "@univerjs-pro/docs-list-ui/lib/index.css",
  "@univerjs-pro/docs-quote-ui/lib/index.css",
  "@univerjs-pro/docs-shape-ui/lib/index.css",
  "@univerjs-pro/docs-table-ui/lib/index.css",
  // Slides.
  "@univerjs-pro/slides-ui/lib/index.css",
  "@univerjs-pro/slides-chart-ui/lib/index.css",
  "@univerjs-pro/slides-table-ui/lib/index.css",
  // Bases.
  "@univerjs-pro/bases-ui/lib/index.css",
  "@univerjs-pro/bases-exchange-client/lib/index.css",
  // Boards and ink.
  "@univerjs-pro/ink-ui/lib/index.css",
  "@univerjs-pro/boards-ui/lib/index.css",
  "@univerjs-pro/boards-chart-ui/lib/index.css",
  "@univerjs-pro/boards-mind-ui/lib/index.css",
  "@univerjs-pro/boards-table-ui/lib/index.css",
  // Shared collaboration/embed controls must come last so their variables
  // and z-index rules match the mounted workbench.
  "@univerjs-pro/collaboration-client-ui/lib/index.css",
  "@univerjs-pro/embed-ui/lib/index.css",
];

let out = "/* GENERATED by scripts/gen-css.mjs — do not edit. */\n";
out += "/* Aggregated Univer preset styles for the DSH-page document viewer. */\n";
for (const spec of [...new Set(SHEETS)]) {
  const css = readFileSync(require.resolve(spec), "utf8");
  out += `\n/* ${spec} */\n${css}\n`;
}
out = out.replace(/[ \t]+$/gmu, "").replace(/\n*$/u, "\n");
writeFileSync(new URL("../src/client/gen-univer.css", import.meta.url), out);
console.log("[gen-css] wrote", SHEETS.length, "stylesheets");
