import type { WorkspaceFileLocale, WorkspaceUnitType } from "./types.js";

export const browserCopy = {
  "zh-CN": {
    actions: "操作",
    openInNewTab: "在新标签页中打开",
    share: "分享",
    copyLink: "复制链接",
    rename: "重命名",
    moveToTrash: "移到回收站",
    move: "移动",
    cancel: "取消",
    save: "保存",
    create: "创建",
    new: "新建",
    uploadFile: "上传文件",
    newDocument: "新建文档",
    group: "文件夹",
    createGroup: "新建文件夹",
    groupName: "文件夹名称",
    resourceName: "文件名称",
    name: "名称",
    enterGroupName: "请输入文件夹名称",
    enterResourceName: "请输入文件名称",
    itemUpdated: "已更新",
    updateFailed: "更新失败",
    movedToTrash: "已移到回收站",
    trashFailed: "移到回收站失败",
    linkCopied: "链接已复制",
    copyLinkFailed: "复制链接失败",
    groupCreated: "文件夹已创建",
    resourceCreated: "文件已创建",
    createFailed: "创建失败",
    fileUploaded: "文件已上传",
    uploadFailed: "文件上传失败",
    itemMoved: "已移动",
    moveFailed: "移动失败",
    editTitle: (name: string) => `重命名“${name}”`,
    trashTitle: (name: string) => `将“${name}”移到回收站？`,
    untitled: (type: string) => `未命名${type}`,
    documentMode: "文档模式",
    modern: "现代模式",
    classic: "传统模式",
    modernDescription: "使用现代文档布局。",
    classicDescription: "使用传统分页文档布局。",
    createTeamSpace: "新建团队空间",
    spaceName: "空间名称",
    enterSpaceName: "请输入空间名称",
    publicRead: "公开只读访问",
    publicReadDescription: "拥有链接的 Workspace 用户可以查看此空间。",
    teamCreated: "团队空间已创建",
    teamCreateFailed: "团队空间创建失败",
    shareTitle: (name: string) => `分享“${name}”`,
    shareDescription: "管理成员访问权限和链接分享。",
    inviteCollaborators: "邀请协作者",
    searchUsers: "搜索用户",
    minTwoChars: "请输入至少两个字符",
    access: "权限",
    accessViewer: "可查看",
    accessEditor: "可编辑",
    accessOwner: "所有者",
    accessAdmin: "管理员",
    invite: "邀请",
    selectUser: "请选择用户",
    accessUpdated: "访问权限已更新",
    accessRemoved: "访问权限已移除",
    sharingUpdateFailed: "分享设置更新失败",
    peopleWithAccess: "已有访问权限的用户",
    peopleCount: (count: number) => `${count} 人`,
    noDirectShares: "暂无直接分享",
    remove: "移除",
    effectiveRole: (role: string) => `有效权限：${role}`,
    linkSharing: "链接分享",
    linkSharingEnabled: "链接分享已开启",
    linkSharingDisabled: "链接分享已关闭",
    linkSharingEnabledDescription: "拥有链接的用户可以按下方权限访问。",
    linkSharingDisabledDescription: "开启后可以通过链接分享此文件。",
    enableLinkSharing: "开启链接分享",
    disableLinkSharing: "关闭链接分享",
    linkSharingOn: "已开启",
    linkSharingOff: "已关闭",
    linkSharingAccess: "链接访问权限",
    linkSharingUpdated: "链接分享已更新",
    privacyNote: "Workspace 服务端仍会根据当前分享设置校验访问权限。",
  },
  "en-US": {
    actions: "Actions",
    openInNewTab: "Open in new tab",
    share: "Share",
    copyLink: "Copy link",
    rename: "Rename",
    moveToTrash: "Move to trash",
    move: "Move",
    cancel: "Cancel",
    save: "Save",
    create: "Create",
    new: "New",
    uploadFile: "Upload file",
    newDocument: "New document",
    group: "Folder",
    createGroup: "Create folder",
    groupName: "Folder name",
    resourceName: "File name",
    name: "Name",
    enterGroupName: "Enter a folder name",
    enterResourceName: "Enter a file name",
    itemUpdated: "Item updated",
    updateFailed: "Update failed",
    movedToTrash: "Moved to trash",
    trashFailed: "Move to trash failed",
    linkCopied: "Link copied",
    copyLinkFailed: "Copy link failed",
    groupCreated: "Folder created",
    resourceCreated: "File created",
    createFailed: "Creation failed",
    fileUploaded: "File uploaded",
    uploadFailed: "File upload failed",
    itemMoved: "Item moved",
    moveFailed: "Move failed",
    editTitle: (name: string) => `Rename “${name}”`,
    trashTitle: (name: string) => `Move “${name}” to trash?`,
    untitled: (type: string) => `Untitled ${type}`,
    documentMode: "Document mode",
    modern: "Modern",
    classic: "Classic",
    modernDescription: "Use the modern document layout.",
    classicDescription: "Use the classic paginated document layout.",
    createTeamSpace: "Create team space",
    spaceName: "Space name",
    enterSpaceName: "Enter a space name",
    publicRead: "Public read access",
    publicReadDescription: "Workspace users with the link can view this space.",
    teamCreated: "Team space created",
    teamCreateFailed: "Team space creation failed",
    shareTitle: (name: string) => `Share “${name}”`,
    shareDescription: "Manage member access and link sharing.",
    inviteCollaborators: "Invite collaborators",
    searchUsers: "Search users",
    minTwoChars: "Enter at least two characters",
    access: "Access",
    accessViewer: "Viewer",
    accessEditor: "Editor",
    accessOwner: "Owner",
    accessAdmin: "Admin",
    invite: "Invite",
    selectUser: "Select a user",
    accessUpdated: "Access updated",
    accessRemoved: "Access removed",
    sharingUpdateFailed: "Sharing update failed",
    peopleWithAccess: "People with access",
    peopleCount: (count: number) => `${count} people`,
    noDirectShares: "No direct shares",
    remove: "Remove",
    effectiveRole: (role: string) => `Effective role: ${role}`,
    linkSharing: "Link sharing",
    linkSharingEnabled: "Link sharing is on",
    linkSharingDisabled: "Link sharing is off",
    linkSharingEnabledDescription: "Anyone with the link can use the access level below.",
    linkSharingDisabledDescription: "Turn this on to share the file by link.",
    enableLinkSharing: "Enable link sharing",
    disableLinkSharing: "Disable link sharing",
    linkSharingOn: "On",
    linkSharingOff: "Off",
    linkSharingAccess: "Link access",
    linkSharingUpdated: "Link sharing updated",
    privacyNote: "The Workspace server continues to enforce the current sharing settings.",
  },
} as const;

export function unitLabel(locale: WorkspaceFileLocale, unitType: WorkspaceUnitType): string {
  const names = {
    "zh-CN": { doc: "文档", sheet: "表格", slide: "幻灯片", board: "白板", base: "数据表" },
    "en-US": { doc: "Document", sheet: "Sheet", slide: "Slides", board: "Board", base: "Base" },
  } as const;
  return names[locale][unitType];
}
